exports.createPost = async (req, res, next) => {
  try {
  } catch (error) {
    console.error('error occured in post route - createPost :: \n', error);
    next(error);
  }
}

exports.getAllPosts = async (req, res, next) => {
  try {
  } catch (error) {
    console.error('error occured in post route - getAllPosts :: \n', error);
    next(error);
  }
}

exports.deletePost = async (req, res, next) => {
  try {
  } catch (error) {
    console.error('error occured in post route - deletePost :: \n', error);
    next(error);
  }
}
